package com.syrf.location.utils

object Constants {

    const val NOTIFICATION_CHANNEL_ID = "SyrfLocationService"
    const val LOCATION_NOTIFICATION_ID = 1001

    const val ACCELERO_NOTIFICATION_CHANNEL_ID = "SyrfAcceleroSensorService"
    const val ACCELERO_NOTIFICATION_ID = 1002

    private const val PACKAGE_NAME = "com.syrf.location"

    const val ACTION_LOCATION_BROADCAST = "$PACKAGE_NAME.action.LOCATION_BROADCAST"
    const val EXTRA_LOCATION = "$PACKAGE_NAME.extra.LOCATION"
    const val EXTRA_CANCEL_LOCATION_TRACKING_FROM_NOTIFICATION =
        "$PACKAGE_NAME.extra.CANCEL_LOCATION_TRACKING_FROM_NOTIFICATION"


    const val ACTION_ACCELERO_SENSOR_BROADCAST = "$PACKAGE_NAME.action.ACCELERO_SENSOR_BROADCAST"
    const val EXTRA_ACCELERO_SENSOR_DATA = "$PACKAGE_NAME.extra.ACCELERO_SENSOR_DATA"
    const val EXTRA_CANCEL_ACCELERO_SENSOR_TRACKING_FROM_NOTIFICATION =
        "$PACKAGE_NAME.extra.CANCEL_ACCELERO_SENSOR_TRACKING_FROM_NOTIFICATION"
}